import { clsx, type ClassValue } from 'clsx';
import { twMerge } from 'tailwind-merge';

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}

export const translations = {
  bn: {
    home: 'হোম',
    tracker: 'হিসাব',
    notes: 'নোটবুক',
    settings: 'সেটিংস',
    income: 'আয়',
    expense: 'ব্যয়',
    balance: 'অবশিষ্ট',
    budget: 'বাজেট',
    add_income: 'আয় যোগ করুন',
    add_expense: 'ব্যয় যোগ করুন',
    set_budget: 'বাজেট সেট করুন',
    total_income: 'মোট আয়',
    total_expense: 'মোট ব্যয়',
    remaining: 'অবশিষ্ট',
    category: 'ক্যাটাগরি',
    amount: 'পরিমাণ',
    note: 'নোট',
    date: 'তারিখ',
    save: 'সংরক্ষণ করুন',
    cancel: 'বাতিল',
    delete: 'মুছে ফেলুন',
    edit: 'সম্পাদনা',
    search: 'খুঁজুন...',
    no_data: 'কোনো তথ্য পাওয়া যায়নি',
    export_pdf: 'পিডিএফ ডাউনলোড',
    language: 'ভাষা',
    reset_data: 'সব তথ্য মুছে ফেলুন',
    confirm_reset: 'আপনি কি নিশ্চিত যে সব তথ্য মুছে ফেলতে চান?',
    daily: 'দৈনিক',
    monthly: 'মাসিক',
    all: 'সব',
    title: 'শিরোনাম',
    content: 'বিস্তারিত',
    add_note: 'নতুন নোট',
    image_upload: 'ছবি আপলোড',
    recent_transactions: 'সাম্প্রতিক লেনদেন',
    summary: 'সারসংক্ষেপ'
  },
  en: {
    home: 'Home',
    tracker: 'Tracker',
    notes: 'Notebook',
    settings: 'Settings',
    income: 'Income',
    expense: 'Expense',
    balance: 'Balance',
    budget: 'Budget',
    add_income: 'Add Income',
    add_expense: 'Add Expense',
    set_budget: 'Set Budget',
    total_income: 'Total Income',
    total_expense: 'Total Expense',
    remaining: 'Remaining',
    category: 'Category',
    amount: 'Amount',
    note: 'Note',
    date: 'Date',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    edit: 'Edit',
    search: 'Search...',
    no_data: 'No data found',
    export_pdf: 'Export PDF',
    language: 'Language',
    reset_data: 'Reset All Data',
    confirm_reset: 'Are you sure you want to reset all data?',
    daily: 'Daily',
    monthly: 'Monthly',
    all: 'All',
    title: 'Title',
    content: 'Content',
    add_note: 'Add Note',
    image_upload: 'Upload Image',
    recent_transactions: 'Recent Transactions',
    summary: 'Summary'
  }
};

export type Language = 'bn' | 'en';
